/**
 * Constants for error codes returned by the server API
 */
export const ErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  CONFLICT: 'CONFLICT',
  CART_HEADER_MISSING: 'CART_HEADER_MISSING',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  MAIL_ERROR: 'MAIL_ERROR',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_PARAMETER: 'MISSING_PARAMETER',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',  
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALUE_ALREADY_EXISTS: 'VALUE_ALREADY_EXISTS'
} as const;

export type ErrorCode = keyof typeof ErrorCodes; 

/**
 * Constants for validation error codes returned by the server API
 */
export const ValidationErrorCodes = {
  REQUIRED: 'REQUIRED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_DIGITS: 'INVALID_DIGITS',
  INVALID_URL: 'INVALID_URL',
  INVALID_LENGTH: 'INVALID_LENGTH',
  TOO_SMALL: 'TOO_SMALL',
  TOO_LARGE: 'TOO_LARGE',
  MUST_BE_POSITIVE: 'MUST_BE_POSITIVE',
  MUST_BE_POSITIVE_OR_ZERO: 'MUST_BE_POSITIVE_OR_ZERO',
  MUST_BE_NEGATIVE: 'MUST_BE_NEGATIVE',
  MUST_BE_NEGATIVE_OR_ZERO: 'MUST_BE_NEGATIVE_OR_ZERO',
  MUST_BE_IN_PAST: 'MUST_BE_IN_PAST',
  MUST_BE_IN_PAST_OR_PRESENT: 'MUST_BE_IN_PAST_OR_PRESENT',
  MUST_BE_IN_FUTURE: 'MUST_BE_IN_FUTURE',
  MUST_BE_IN_FUTURE_OR_PRESENT: 'MUST_BE_IN_FUTURE_OR_PRESENT',  
  MUST_BE_TRUE: 'MUST_BE_TRUE',
  MUST_BE_FALSE: 'MUST_BE_FALSE',
  INVALID_TYPE: 'INVALID_TYPE',
  VALUE_ALREADY_EXISTS: 'VALUE_ALREADY_EXISTS',  
  INVALID_FIELD: 'INVALID_FIELD',
  INVALID_NESTED_FIELD: 'INVALID_NESTED_FIELD'
} as const;

export type ValidationErrorCode = keyof typeof ValidationErrorCodes;