/**
 * Constants for error codes returned by the server API
 */
export const ErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  CONFLICT: 'CONFLICT',
  CART_HEADER_MISSING: 'CART_HEADER_MISSING',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  MAIL_ERROR: 'MAIL_ERROR',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_PARAMETER: 'MISSING_PARAMETER',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',  
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALUE_ALREADY_EXISTS: 'VALUE_ALREADY_EXISTS'
} as const;

export type ErrorCode = keyof typeof ErrorCodes; 